### ISSUE TITLE
Sleepless bug(s)

### ISSUE THREAD

**Issue by andilem** [vincitego/vincitego.github.io#85]
Sleepless currently heals himself with 30% probability for 10% HP not only when he is hit by an enemy, but for *every* enemy basic or active.

Also, I don't know if his active is implemented correctly and he applies an additional mark on every enemy with 45% prob, or if he just applies an additional mark with 45% prob on a random enemy. The skill description is not clear for me.

**Comment by vincitego** [comment]
Thanks, and sorry for the slow reply, I've been busy working on a different project. 

I'll push a fix soon for the heal. As for Sleepless' active, the in game text is unclear, but Samogot's data mining spreadsheet does indicate that they all have a 45% chance of getting the extra mark.

**Comment by andilem** [comment]
Thanks for checking that. I only found that bug because I'm wondering why Sleepless is in my genetic optimizations always ranked 4th, only behind Carrie, Sherlock and Garuda.
But even with the heal fix and the (as you said probably wrong) nerf, he comes still out 4th.
Seems to be a strange synergy between multiple Carries and him, because he is also Dark and can resurrect.
But then, it's unclear (at least for me) why Michelle doesn't play any role.

The other heroes which don't perform as I would expect are Russell (ranked 5th, but keeps killing me in the game) and Aida (ranked ~10, but should be better IMHO). But I didn't look at the code for them yet.

**Comment by vincitego** [comment]
Hmm, that's weird, Sleepless is usually ranked at the bottom for me and Russell in the top 3.
